### ISSUE TITLE
a screenshot says more than 1000words...

### ISSUE THREAD

**Issue by hpvd** [firegento/firegento-customer#13]
since this extension seems not to be available via magento connect one could not find any screenshot of
- the configuration options or
- the messages if the the password is validated 
  maybe you could but 2-3 screenshots e.g. on http://firegento.com/modules/customer/ ?

=> would make it even more attractive to try/use this extension

**Comment by Schrank** [comment]
hpvd you are kindly invited to do so! :-)

**Comment by therouv** [comment]
Hi @hpvd 
Please have a look at https://github.com/firegento/firegento-customer/tree/develop#description - It's not merged in master branch yet.
