### ISSUE TITLE
Unable to choose a category and save it 

### ISSUE THREAD

**Issue by seemaalbal** [firegento/firegento-customer#14]
Hi, I just installed this extension.

However, in my new category (currently inactive), I use the dynamic category product relater. 
I choose with these conditions: Category is -> Open the chooser, choose a category and click the green tick box. However, the category is not chosen. I want to add atleast 4-5 categories. 

How does this work?

I think this is the wrong column!!

**Comment by Schrank** [comment]
Wrong project: https://github.com/firegento/firegento-dynamiccategory/issues/43
