### ISSUE TITLE
Grouped products are not being picked up

### ISSUE THREAD

**Issue by mattc-YMB** [firegento/firegento-customer#20]
For some reason I noticed that if a product is type grouped the dynamic categories does not pick them up. I have not tried for bundled yet. I dont understand why all attribute are the same in the child as father. Re index etc. Thank you for any help I dont want to have to change this extension as it has worked well up to now.  magento  1.9.4.3 DynamicCategory =Version: 1.2.2
Mattc

**Comment by Schrank** [comment]
Hi @mattc-YMB I'm pretty sure this issue belongs to https://github.com/firegento/firegento-dynamiccategory ?
