### ISSUE TITLE
login Parameter werden nicht erkannt

### ISSUE THREAD

**Issue by Celldweller** [firegento/firegento-customer#3]
Ich erlebe bei mir das Phänomen, das die validateCustomerActivationBeforeLogin Methode im Observer das login Parameter Array nicht korrekt ermitteln kann.

Wenn ich 
$loginParams = $controller->getRequest()->getParams('login');
debugge, dann erhalte ich so etwas:

Array
(
    [login] => Array
        (
            [username] => xxx@xxx.com
            [password] => 111111
        )

```
[send] => 
```

)

Also ein Array, indem das login Object erst enthalten ist.
Das Modul funktioniert bei mir demzufolge nur, wenn ich nach der o.g. Zeile noch zusätzlich einfüge:
$loginParams = $loginParams['login'];

Shopversion ist 1.7.0.0

Frage ist: Hat es was mit der Magentoversion zu tun?
Aus meiner Sicht ist kein anderes Modul an dieser Stelle in meiner Installation beteiligt.

VG
Celldweller

**Comment by mklooss** [comment]
getParams(), hat garkein Parameter zum übergeben, da hättest du getParam verwenden müssen.
diesen Bug hatte ich vor 4 Monaten gefixed.

(und ja ich weiss das das Thema alt ist)
