### ISSUE TITLE
Probleme mit translate.csv

### ISSUE THREAD

**Issue by Celldweller** [firegento/firegento-customer#4]
Vor der Installation des Moduls habe ich eine funktionierende ersetzende Übersetzung für "Invalid login or password." in der translate.csv meines eigenen Themes gehabt.

Sobald jedoch das FireGento_Customer aktiviert wird, funktioniert diese nicht mehr. Magento holt sich nur noch die Standardübersetzung aus der app/locale/de_DE/Mage_Customer.csv

Erst wenn ich in meiner translate.csv explizit auf "Mage_Customer::Invalid login or password." verweise, wird meine Übersetzung wieder verwendet.
Wie kommt das?

Ich glaube nicht, dass es ein Bug von FireGento_Customer ist, aber trotzdem ist es ein seltsames Verhalten. Vielleicht hat jemand eine Idee?

Viele Grüße
Celldweller

**Comment by mklooss** [comment]
ist zwar schon lange her ist aber ein "Bug" vom Modul...
mit meinem Pull Request #8 ist der Bug behoben.

Du hättest statt "Mage_Customer::" dann "FireGento_Customer::" schreiben müssen.

(und ja ich weiss das das Thema alt ist)
